export const types = {
	SHOW_POPUP: 'SHOW_POPUP',
	SHOW_CLOSE: 'SHOW_CLOSE',
	SHOW_ERROR: 'SHOW_ERROR',
	CLOSE_ERROR: 'CLOSE_ERROR',
	SHOW_ADD_GROUP_POP_UP: 'SHOW_ADD_GROUP_POP_UP',
	CLOSE_ADD_GROUP_POP_UP: 'CLOSE_ADD_GROUP_POP_UP',

	SET_ID_FIRST_TABLE: 'SET_ID_FIRST_TABLE',
	CLEAR_SELECTED_ID_FIRST: 'CLEAR_SELECTED_ID_FIRST',
	ADD_ROW_FIRST_TABLE: 'ADD_ROW_FIRST_TABLE',
	DELETE_ROW_FIRST_TABLE: 'DELETE_ROW_FIRST_TABLE',

	SET_ID_SECOND_TABLE: 'SET_ID_SECOND_TABLE',
	CLEAR_SELECTED_ID_SECOND: 'CLEAR_SELECTED_ID_SECOND',
	DELETE_ROW_SECOND_TABLE: 'DELETE_ROW_SECOND_TABLE',

	SET_ID_THIRD_TABLE: 'SET_ID_THIRD_TABLE',
	CLEAR_SELECTED_ID_THIRD: 'CLEAR_SELECTED_ID_THIRD',
	DELETE_ROW_THIRD_TABLE: 'DELETE_ROW_THIRD_TABLE',

	//SYNC
	PUT_FIRST_TABLE: 'PUT_FIRST_TABLE',
	PUT_SECOND_TABLE: 'PUT_SECOND_TABLE',
	PUT_THIRD_TABLE: 'PUT_THIRD_TABLE',

	//ASYNC
	GET_FIRST_TABLE_ASYNC: 'GET_FIRST_TABLE_ASYNC',
	GET_SECOND_TABLE_ASYNC: 'GET_SECOND_TABLE_ASYNC',
	GET_THIRD_TABLE_ASYNC: 'GET_THIRD_TABLE_ASYNC',
	POST_SAVE: 'POST_SAVE',

	PUT_GROUPS:'PUT_GROUPS'
};
